const documents=[
    {
      id: 1,
      title: 'General Register - Labor Laws 2018',
      category: 'GR',
      type: 'PDF',
      date: 'Mar 12, 2018',
      size: '3.7 MB',
      location:"C:\\Users\\manoj\\Desktop\\Database\\General Register - Labor Laws 2018.pdf",
    },
    {
      id: 2,
      title: 'Minimum Wage Notification for Textile Industry',
      category: 'Notification',
      type: 'PDF',
      date: 'Jul 01, 2023',
      size: '1.8 MB',
      location:"C:\\Users\\manoj\\Desktop\\Database\\Industrial Relations Act Amendment.pdf",
    },
    {
      id: 3,
      title: 'Safety Guidelines for Chemical Industries',
      category: 'Guidelines',
      type: 'DOCX',
      date: 'Sep 15, 2022',
      size: '5.7 MB',
      location:"C:\\Users\\manoj\\Desktop\\Database\\Minimum Wage Notification for Textile Industry.pdf",
    },
    {
      id: 4,
      title: 'Industrial Relations Act Amendment',
      category: 'Amendment',
      type: 'PDF',
      date: 'Nov 30, 2021',
      size: '1.0 MB',
      location:"C:\\Users\\manoj\\Desktop\\Database\\Safety Guidelines for Chemical Industries.docx.pptx",
    },
    {
      id: 5,
      title: 'Maternity Benefit Extension Proposal',
      category: 'Proposal',
      type: 'DOCX',
      date: 'Aug 25, 2023',
      size: '63 KB',
      location:"C:\\Users\\manoj\\Desktop\\Database\\Maternity Benefit Extension Proposal.docx",
    },
    {
      id: 6,
      title: 'Special Economic Zone Labor Guidelines',
      category: 'Guidelines',
      type: 'PDF',
      date: 'Jan 10, 2023',
      size: '1.5 MB',
      location:"C:\\Users\\manoj\\Desktop\\Database\\Special Economic Zone Labor Guidelines.pdf",
    },
    {
      id: 7,
      title: 'Contract Labor Regulation Act - 2022 Amendment',
      category: 'Amendment',
      type: 'PDF',
      date: 'May 20, 2022',
      size: '0.2 MB',
      location:"C:\\Users\\manoj\\Desktop\\Database\\Contract Labor Regulation Act - 2022 Amendment.pdf",
    },
    {
      id: 8,
      title: 'Factory Safety Standards - Chemical Sector',
      category: 'Standards',
      type: 'PDF',
      date: 'Apr 05, 2023',
      size: '0.2 MB',
      location:"C:\\Users\\manoj\\Desktop\\Database\\Factory Safety Standards - Chemical Sector.pdf",
    },
    {
      id: 9,
      title: 'Employee State Insurance Guidelines',
      category: 'Guidelines',
      type: 'PDF',
      date: 'Jun 18, 2022',
      size: '0.3 MB',
      location:"C:\\Users\\manoj\\Desktop\\Database\\Employee State Insurance Guidelines.pdf",
    },
    {
      id: 10,
      title: 'Labor Law Compliance Checklist',
      category: 'Checklist',
      type: 'XLSX',
      date: 'Jul 22, 2023',
      size: '43 KB',
      location:"C:\\Users\\manoj\\Desktop\\Database\\Labor Law Compliance Checklist.xls",
    },
    {
      id: 11,
      title: 'General Register - Wage Disputes 2022',
      category: 'GR',
      type: 'PDF',
      date: 'Dec 15, 2022',
      size: '0.2 MB',
      location:"C:\\Users\\manoj\\Desktop\\Database\\General Register - Wage Disputes 2022.pdf",
    },
    {
      id: 12,
      title: 'Annual Labor Report - Gujarat 2022',
      category: 'Report',
      type: 'PDF',
      date: 'Feb 28, 2023',
      size: '5.4 MB',
      location:"C:\\Users\\manoj\\Desktop\\Database\\Annual Labor Report - Gujarat 2022.pdf",
    },
    {
        id: 13,
        title: 'High Court Ruling on Environmental Regulations',
        category: 'Report',
        type: 'PDF',
        date: 'Jun 28, 2022',
        size: '3.8 MB', 
        location:"C:\\Users\\manoj\\Desktop\\Database\\High Court Ruling on Environmental Regulations.pdf",
    },
    {
        id: 14,
        title: 'The Information Technology Act',
        category: 'Act',
        type: 'PDF',
        date: 'Jun 28, 2000',
        size: '0.4 MB',
        location:"C:\\Users\\manoj\\Desktop\\Database\\The Information Technology Act.pdf",
    },
    {
        id: 15,
        title: 'Legislative Acts Reference Table',
        category: 'Checklist',
        type: 'XLSX',
        date: 'Jun 28, 2000',
        size: '25 KB',
        location:"C:\\Users\\manoj\\Desktop\\Database\\Legislative Acts Reference Table.xlsx",
    },
    {
        id: 16,
        title: 'Legal Notices and Circulars Summary',
        category: 'Checklist',
        type: 'XLSX',
        date: 'Jul 09, 2022',
        size: '61 KB',
        location:"C:\\Users\\manoj\\Desktop\\Database\\Legal Notices and Circulars Summary.xlsx",
    },
    {
        id: 17,
        title: 'RBI Circular on Loan Moratorium Extension',
        category: 'GR',
        type: 'DOCX',
        date: 'Apr 2018',
        size: '11 KB',
        location:"C:\\Users\\manoj\\Desktop\\Database\\RBI Circular on Loan Moratorium Extension.docx",
    }

  ]
  export default documents;